---
- hosts: local
  tasks:
   - name: Generate configs
     template: src=./ex3_config.txt dest=./ex3_{{item.hostname}}.txt
     with_items:
       - {hostname: rtr1, SNMPV3: False, ip_addr: 192.168.1.10, access_vlan: 10, snmp_community: readonly, secret: whisper, default_gateway: 192.168.1.1 }
       - {hostname: rtr2, SNMPV3: True, ip_addr: 192.168.2.10, access_vlan: 10, snmp_community: readonly, secret: whisper, default_gateway: 192.168.2.1 }
       - {hostname: rtr3, SNMPV3: True, ip_addr: 192.168.3.10, access_vlan: 10, snmp_community: readonly, secret: whisper, default_gateway: 192.168.3.1 }
       - {hostname: rtr4, SNMPV3: True, ip_addr: 192.168.4.10, access_vlan: 10, snmp_community: readonly, secret: whisper, default_gateway: 192.168.4.1 }
       - {hostname: rtr5, SNMPV3: True, ip_addr: 192.168.5.10, access_vlan: 10, snmp_community: readonly, secret: whisper, default_gateway: 192.168.5.1 }
