---

- name: EX2
  hosts: arista
  
  tasks:
   - name: Set Ethernet2 Description 
     eos_interface: name=Ethernet2 description="*** IN USE ***"
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
   - name: Set Ethernet2 Trunk 
     eos_switchport: name=Ethernet2 mode=access access_vlan=448
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
