---

- name: EX5
  hosts: pynet-rtr1
  gather_facts: False
  
  tasks:
  - name: File Transfer
    cisco_file_transfer:
      source_file="/home/jbonner/ANSIBLE/test_file.txt"
      dest_file="test_file.txt"
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
